
-- Equipo Rosa
-- Eduardo Mendoza Izquierdo
-- Carlos de Jesus Brindis Martinez
-- Jairo Bayona Hernandez
-- Edgar Jesus Carrillo Mendoza


-- Esquema PostgreSQL para bd del proyecto BarberSaas
-- Solo incluye tablas de negocio del proyecto.
-- No incluye tablas internas de Django: auth_*, django_*, sessions, etc.

-- =========================================================
-- BARBERS
-- =========================================================

CREATE TABLE barber_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    color_code VARCHAR(7) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE barbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    nickname VARCHAR(100) NULL,
    email VARCHAR(254) NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    description TEXT NULL,
    avatar VARCHAR(255) NULL,
    color_code VARCHAR(7) NOT NULL,
    status_id BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_barbers_status
        FOREIGN KEY (status_id)
        REFERENCES barber_status(id)
        ON DELETE RESTRICT
);

CREATE TABLE barber_specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id BIGINT NOT NULL,
    specialty_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_barber_specialties_barber
        FOREIGN KEY (barber_id)
        REFERENCES barbers(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_barber_specialties_specialty
        FOREIGN KEY (specialty_id)
        REFERENCES specialties(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_barber_specialties_barber_specialty
        UNIQUE (barber_id, specialty_id)
);

-- =========================================================
-- CLIENTS
-- =========================================================

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(254) NULL UNIQUE,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

-- =========================================================
-- SERVICES
-- =========================================================

CREATE TABLE type_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    short_description VARCHAR(200) NULL,
    price NUMERIC(10, 2) NOT NULL,
    duration INTEGER NOT NULL,
    image_url VARCHAR(255) NULL,
    service_type_id BIGINT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_services_service_type
        FOREIGN KEY (service_type_id)
        REFERENCES type_services(id)
        ON DELETE SET NULL
);

CREATE TABLE service_barbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL,
    barber_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_service_barbers_service
        FOREIGN KEY (service_id)
        REFERENCES services(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_service_barbers_barber
        FOREIGN KEY (barber_id)
        REFERENCES barbers(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_service_barbers_service_barber
        UNIQUE (service_id, barber_id)
);

-- =========================================================
-- APPOINTMENTS
-- =========================================================

CREATE TABLE status_appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barber_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    notes TEXT NULL,
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_duration INTEGER NOT NULL DEFAULT 0,
    confirmation_code VARCHAR(10) NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_appointments_barber
        FOREIGN KEY (barber_id)
        REFERENCES barbers(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_appointments_client
        FOREIGN KEY (client_id)
        REFERENCES clients(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_appointments_status
        FOREIGN KEY (status_id)
        REFERENCES status_appointments(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_appointments_barber_date_time
        UNIQUE (barber_id, date, time)
);

CREATE TABLE appointments_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    price_snapshot NUMERIC(10, 2) NOT NULL,
    duration_snapshot INTEGER NOT NULL,

    CONSTRAINT fk_appointments_services_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES appointments(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_appointments_services_service
        FOREIGN KEY (service_id)
        REFERENCES services(id)
        ON DELETE RESTRICT
);

-- =========================================================
-- BUSINESS SETTINGS
-- =========================================================

CREATE TABLE business_settings (
    id INTEGER PRIMARY KEY DEFAULT 1,
    business_name VARCHAR(100) NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(254) NULL,
    logo_url VARCHAR(255) NULL,
    facebook_url VARCHAR(200) NULL,
    instagram_url VARCHAR(200) NULL,
    tiktok_url VARCHAR(200) NULL,
    opening_time TIME NULL,
    closing_time TIME NULL,
    time_slot_duration INTEGER NOT NULL DEFAULT 30,
    booking_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    max_days_advance INTEGER NOT NULL DEFAULT 30,
    min_hours_before INTEGER NOT NULL DEFAULT 2,
    allow_cancellations BOOLEAN NOT NULL DEFAULT TRUE,
    cancellation_hours_before INTEGER NOT NULL DEFAULT 24,
    require_deposit BOOLEAN NOT NULL DEFAULT FALSE,
    deposit_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE business_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week INTEGER NOT NULL UNIQUE,
    is_working BOOLEAN NOT NULL DEFAULT TRUE,
    opening_time TIME NULL,
    closing_time TIME NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    reason VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE notification_settings (
    id INTEGER PRIMARY KEY DEFAULT 1,
    sms_reminder_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    sms_hours_before INTEGER NOT NULL DEFAULT 24,
    email_promotions_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    whatsapp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    whatsapp_number VARCHAR(20) NULL,
    whatsapp_connected BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL
);

-- =========================================================
-- GALLERY
-- =========================================================

CREATE TABLE gallery_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    slug VARCHAR(50) NOT NULL UNIQUE,
    description TEXT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NULL,
    image_url VARCHAR(255) NOT NULL,
    category_id BIGINT NOT NULL,
    barber_id BIGINT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_gallery_category
        FOREIGN KEY (category_id)
        REFERENCES gallery_categories(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_gallery_barber
        FOREIGN KEY (barber_id)
        REFERENCES barbers(id)
        ON DELETE SET NULL
);

-- =========================================================
-- FINANCE
-- =========================================================

CREATE TABLE category_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE type_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    appointment_id BIGINT NULL,
    concept VARCHAR(200) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    date DATE NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_financial_transactions_type
        FOREIGN KEY (type_id)
        REFERENCES type_transactions(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_financial_transactions_category
        FOREIGN KEY (category_id)
        REFERENCES category_transactions(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_financial_transactions_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES appointments(id)
        ON DELETE SET NULL
);

-- =========================================================
-- ÍNDICES PARA FOREIGN KEYS
-- =========================================================

CREATE INDEX idx_barbers_status_id ON barbers(status_id);
CREATE INDEX idx_barber_specialties_barber_id ON barber_specialties(barber_id);
CREATE INDEX idx_barber_specialties_specialty_id ON barber_specialties(specialty_id);

CREATE INDEX idx_services_service_type_id ON services(service_type_id);
CREATE INDEX idx_service_barbers_service_id ON service_barbers(service_id);
CREATE INDEX idx_service_barbers_barber_id ON service_barbers(barber_id);

CREATE INDEX idx_appointments_barber_id ON appointments(barber_id);
CREATE INDEX idx_appointments_client_id ON appointments(client_id);
CREATE INDEX idx_appointments_status_id ON appointments(status_id);

CREATE INDEX idx_appointments_services_appointment_id ON appointments_services(appointment_id);
CREATE INDEX idx_appointments_services_service_id ON appointments_services(service_id);

CREATE INDEX idx_gallery_category_id ON gallery(category_id);
CREATE INDEX idx_gallery_barber_id ON gallery(barber_id);

CREATE INDEX idx_financial_transactions_type_id ON financial_transactions(type_id);
CREATE INDEX idx_financial_transactions_category_id ON financial_transactions(category_id);
CREATE INDEX idx_financial_transactions_appointment_id ON financial_transactions(appointment_id);
