FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY  entrypoint.dev.sh .
RUN chmod +x entrypoint.dev.sh

COPY init.sql /app/init.sql

EXPOSE 8000

CMD ["./entrypoint.dev.sh"]
