[pytest]
DJANGO_SETTINGS_MODULE = barbersaas.settings
python_files = tests/*.py tests/**/*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=apps --cov-report=term-missing