# Generated by Django 6.0.2 on 2026-02-28 05:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duracion en minutos')),
                ('image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='service_image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
                'db_table': 'type_services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBarber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(db_column='barber_id', on_delete=django.db.models.deletion.CASCADE, to='barbers.barber')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Barbero del Servicio',
                'verbose_name_plural': 'Barberos del Servicio',
                'db_table': 'service_barbers',
                'unique_together': {('service', 'barber')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='barbers',
            field=models.ManyToManyField(related_name='services', through='services.ServiceBarber', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(blank=True, db_column='service_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicetype'),
        ),
    ]
