# Generated by Django 6.0.2 on 2026-02-28 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Transaccion',
                'verbose_name_plural': 'Categorias de Transacciones',
                'db_table': 'category_transactions',
            },
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Transaccion',
                'verbose_name_plural': 'Tipos de Transacciones',
                'db_table': 'type_transactions',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(help_text='Descripcion breve del movimiento', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positivo para ingresos, Negativo para egresos', max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='appointments.appointment')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finance.categorytransaction')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finance.typetransaction')),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'db_table': 'financial_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
