# Generated by Django 6.0.2 on 2026-02-28 21:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], unique=True)),
                ('is_working', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios del Negocio',
                'db_table': 'business_hours',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='business_logo')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('time_slot_duration', models.IntegerField(default=30)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('max_days_advance', models.IntegerField(default=30)),
                ('min_hours_before', models.IntegerField(default=2)),
                ('allow_cancellations', models.BooleanField(default=True)),
                ('cancellation_hours_before', models.IntegerField(default=24)),
                ('require_deposit', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
                'verbose_name_plural': 'Configuración del Negocio',
                'db_table': 'business_settings',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Día Feriado',
                'verbose_name_plural': 'Días Feriados',
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('sms_reminder_enabled', models.BooleanField(default=False)),
                ('sms_hours_before', models.IntegerField(default=24)),
                ('email_promotions_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_connected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuración de Notificaciones',
                'db_table': 'notification_settings',
            },
        ),
    ]
