# Generated by Django 6.0.2 on 2026-02-28 05:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Galeria',
                'verbose_name_plural': 'Categorias de Galeria',
                'db_table': 'gallery_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery_name')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(blank=True, db_column='barber_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='barbers.barber')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='gallery.gallerycategory')),
            ],
            options={
                'verbose_name': 'Imagen de Galeria',
                'verbose_name_plural': 'Imagenes de Galeria',
                'db_table': 'gallery',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
