"""
Django settings for barbersaas project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


import os 
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG','False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    'drf_spectacular',
    'apps.barbers',
    'apps.services',
    'apps.clients',
    'apps.appointments',
    'apps.gallery',
    'apps.finance',
    'apps.core',
    'apps.authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'barbersaas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barbersaas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':     os.getenv('DB_NAME'),
        'USER':     os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST':     os.getenv('DB_HOST'),
        'PORT':     os.getenv('DB_PORT'),
    }
}


#Cors Configuration

CORS_ALLOWED_HOST = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
CORS_ALLOW_CREDENTIALS = True


#Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':10,
    'DEFAULT_SCHEMA_CLASS':'drf_spectacular.openapi.AutoSchema',
}

#Toke JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM':'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES':('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES':('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIMS':'token_type',
}



#Spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE':'BarberSaas API',
    'DESCRIPTION':'''
    API REST para sistema de gestión de barbería.
        
        ## Autenticación
        Usa JWT Bearer token. Para obtener el token:
        1. POST /api/admin/auth/login/ con tus credenciales
        2. Copia el campo "access" de la respuesta
        3. Úsalo en el header: Authorization: Bearer {token}
        
        ## Módulos Públicos
        No requieren autenticación: team, services, gallery, appointments
        
        ## Módulos Admin
        Requieren autenticación JWT: dashboard, finance, reports, agenda, etc.
    ''',
    'VERSION':'1.0.0',
    'SERVE_INCLUDE_SCHEMA':False,

    #Configuracion del boton authorization en swagger UI
    'SECURITY':[{'BearerAuth':[]}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },

    # Organizar endpoints por tags (agrupados en la UI)
    'TAGS': [
        {'name': 'Auth', 'description': 'Autenticación JWT'},
        {'name': 'Public - Team', 'description': 'Barberos (público)'},
        {'name': 'Public - Services', 'description': 'Servicios (público)'},
        {'name': 'Public - Gallery', 'description': 'Galería (público)'},
        {'name': 'Public - Appointments', 'description': 'Agendamiento (público)'},
        {'name': 'Admin - Dashboard', 'description': 'Dashboard'},
        {'name': 'Admin - Finance', 'description': 'Finanzas'},
        {'name': 'Admin - Reports', 'description': 'Reportes'},
        {'name': 'Admin - Agenda', 'description': 'Agenda'},
        {'name': 'Admin - Clients', 'description': 'Clientes'},
        {'name': 'Admin - Services', 'description': 'Servicios CRUD'},
        {'name': 'Admin - Barbers', 'description': 'Equipo CRUD'},
        {'name': 'Admin - Settings', 'description': 'Configuraciones'},
        {'name': 'Admin - Rules - Settings', 'description': 'Reglas de reservas'},
        {'name': 'Admin - Hours - Settings', 'description': 'Horarios del negocio'},
        {'name': 'Admin - Holiday - Settings', 'description': 'Días feriados'},
        {'name': 'Admin - Notification - Settings', 'description': 'Notificaciones'},
        {'name': 'Admin - Barbers - Specialties', 'description': 'Especialidades'},
        {'name': 'Admin - Category - Gallery', 'description': 'Categorías de galería'},
        {'name': 'Admin - Category - Finance', 'description': 'Categorías de finanzas'},
        {'name': 'Admin - Type - Finance', 'description': 'Tipos de transacción'},
    ],

}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import cloudinary

#Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET')
}

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key=CLOUDINARY_STORAGE['API_KEY'],
    api_secret=CLOUDINARY_STORAGE['API_SECRET'],
    secure=True
)

# Archivos media (imágenes subidas por el admin)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'