# Generated by Django 6.0.2 on 2026-02-28 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado de Cita',
                'verbose_name_plural': 'Estados de Citas',
                'db_table': 'status_appointments',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_duration', models.IntegerField(default=0, help_text='Duracion total en minutos')),
                ('confirmation_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(db_column='barber_id', on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='barbers.barber')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='clients.client')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'appointments',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_snapshot', models.IntegerField()),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.RESTRICT, to='services.service')),
            ],
            options={
                'verbose_name': 'Servicio de la Cita',
                'verbose_name_plural': 'Servicios de la Cita',
                'db_table': 'appointments_services',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', through='appointments.AppointmentService', to='services.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, to='appointments.statusappoinment'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('barber', 'date', 'time')},
        ),
    ]
